config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root :to => "lessons#index"
  # Routes for the Cancellation_note resource:
  # CREATE
  get "/cancellation_notes/new", :controller => "cancellation_notes", :action => "new"
  post "/create_cancellation_note", :controller => "cancellation_notes", :action => "create"

  # READ
  get "/cancellation_notes", :controller => "cancellation_notes", :action => "index"
  get "/cancellation_notes/:id", :controller => "cancellation_notes", :action => "show"

  # UPDATE
  get "/cancellation_notes/:id/edit", :controller => "cancellation_notes", :action => "edit"
  post "/update_cancellation_note/:id", :controller => "cancellation_notes", :action => "update"

  # DELETE
  get "/delete_cancellation_note/:id", :controller => "cancellation_notes", :action => "destroy"
  #------------------------------

  # Routes for the Lesson resource:
  # CREATE
  get "/lessons/new/:id", :controller => "lessons", :action => "new"
  post "/create_lesson", :controller => "lessons", :action => "create"

  # READ
  get "/lessons", :controller => "lessons", :action => "index"
  get "/lessons/detail/:id", :controller => "lessons", :action => "show"
  get "/lessons/:id", :controller => "lessons", :action => "index"

  # UPDATE
  get "/lessons/:id/edit", :controller => "lessons", :action => "edit"
  post "/update_lesson/:id", :controller => "lessons", :action => "update"

  # DELETE
  get "/delete_lesson/:id", :controller => "lessons", :action => "destroy"
  #------------------------------

  # Routes for the Break resource:
  # CREATE
  get "/breaks/new", :controller => "breaks", :action => "new"
  post "/create_break", :controller => "breaks", :action => "create"

  # READ
  get "/breaks", :controller => "breaks", :action => "index"
  get "/breaks/:id", :controller => "breaks", :action => "show"

  # UPDATE
  get "/breaks/:id/edit", :controller => "breaks", :action => "edit"
  post "/update_break/:id", :controller => "breaks", :action => "update"

  # DELETE
  get "/delete_break/:id", :controller => "breaks", :action => "destroy"
  #------------------------------

  # Routes for the Schedule_adjustment resource:
  # CREATE
  get "/schedule_adjustments/new", :controller => "schedule_adjustments", :action => "new"
  post "/create_schedule_adjustment", :controller => "schedule_adjustments", :action => "create"

  # READ
  get "/schedule_adjustments", :controller => "schedule_adjustments", :action => "index"
  get "/schedule_adjustments/:id", :controller => "schedule_adjustments", :action => "show"

  # UPDATE
  get "/schedule_adjustments/:id/edit", :controller => "schedule_adjustments", :action => "edit"
  post "/update_schedule_adjustment/:id", :controller => "schedule_adjustments", :action => "update"

  # DELETE
  get "/delete_schedule_adjustment/:id", :controller => "schedule_adjustments", :action => "destroy"
  #------------------------------

  # Routes for the Trainer resource:
  # CREATE
  get "/trainers/new", :controller => "trainers", :action => "new"
  post "/create_trainer", :controller => "trainers", :action => "create"

  # READ
  get "/trainers", :controller => "trainers", :action => "index"
  get "/trainers/:id", :controller => "trainers", :action => "show"

  # UPDATE
  get "/trainers/:id/edit", :controller => "trainers", :action => "edit"
  post "/update_trainer/:id", :controller => "trainers", :action => "update"

  # DELETE
  get "/delete_trainer/:id", :controller => "trainers", :action => "destroy"
  #------------------------------


  # Routes for My Lessons:
  # READ
  get "/my_lessons/:id", :controller => "my_lessons", :action => "index"


  #------------------------------

  devise_for :students
  # Routes for the Student resource:
  # READ
  get "/students", :controller => "students", :action => "index"
  get "/students/:id", :controller => "students", :action => "show"


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  # Direct associations

  has_one    :cancellation_note,
             :dependent => :destroy

  belongs_to :trainer

  belongs_to :student,
             :counter_cache => true

  # Indirect associations

  # Validations

  validates :lesson_time, :presence => true

  validates :student_id, :uniqueness => { :scope => [:lesson_time], :message => "You already have a lesson at this time." }

  validates :student_id, :presence => true

  validates :trainer_id, :uniqueness => { :scope => [:lesson_time], :message => "Trainer is already booked" }

  validates :trainer_id, :presence => true

end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController

  def current_user_must_be_lesson_student
    lesson = Lesson.find(params[:id])

    unless current_user == lesson.student
      redirect_to :back, :alert => "You are not authorized for that."
    end
  end

  def index
    @lesson_options = ['9:00 AM', '9:30 AM', '10:00 AM', '10:30 AM', '11:00 AM', '11:30 AM', '12:00 PM', '12:30 PM', '1:00 PM', '1:30 PM', '2:00 PM', '2:30 PM', '3:00 PM', '3:30 PM', '4:00 PM', '4:30 PM', '5:00 PM', '5:30 PM', '6:00 PM', '6:30 PM', '7:00 PM', '7:30 PM']
    @weekday = ['Tues', 'Wed', 'Thurs', 'Fri', 'Sat', 'Sun']
    @q = Lesson.ransack(params[:q])
    @lessons = @q.result(:distinct => true).includes(:student, :trainer, :cancellation_note)

    @week = params[:id]
    render("lessons/index.html.erb")
  end

  def show
    @lesson = Lesson.find(params[:id])

    render("lessons/show.html.erb")
  end

  def new
    @lesson = Lesson.new
    @trainers = Trainer.all

    @time = params[:id]
    @cleantime = @time.gsub( "_", " ")
    @chronictime = Chronic.parse(@cleantime)

    @referer = URI(request.referer).path

    render("lessons/new.html.erb")
  end

  def create
    @lesson = Lesson.new

    @lesson.trainer_id = params[:trainer_id]
    @lesson.lesson_time = params[:lesson_time]
    @lesson.student_id = params[:student_id]

    save_status = @lesson.save

    @lesson_page = params[:lesson_page]

    redirect_to("#{@lesson_page}", :notice => "Lesson added")
  end

  def edit
    @lesson = Lesson.find(params[:id])

    render("lessons/edit.html.erb")
  end

  def update
    @lesson = Lesson.find(params[:id])

    @lesson.trainer_id = params[:trainer_id]
    @lesson.lesson_time = params[:lesson_time]
    @lesson.student_id = params[:student_id]

    save_status = @lesson.save

    if save_status == true
      referer = URI(request.referer).path

      case referer
      when "/lessons/#{@lesson.id}/edit", "/update_lesson"
        redirect_to("/lessons/#{@lesson.id}", :notice => "Lesson updated successfully.")
      else
        redirect_back(:fallback_location => "/", :notice => "Lesson updated successfully.")
      end
    else
      render("lessons/edit.html.erb")
    end
  end

  def destroy
    @lesson = Lesson.find(params[:id])

    @lesson.destroy

      redirect_to("/", :notice => "Lesson deleted.")
  end
end

app/views/lessons/edit.html.erb
<!-- Validation failure messages -->
<% if @lesson.errors.any? %>
  <% @lesson.errors.full_messages.each do |message| %>
    <div class="alert alert-dismissable alert-danger">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= message %>
    </div>
  <% end %>
<% end %>

<div class="page-header">
  <h3>Edit Lesson #<%= @lesson.id %></h3>
</div>

<div class="row">
  <div class="col-md-12">
    <form action="/update_lesson/<%= @lesson.id %>" method="post">
      <!-- Hidden input for authenticity token to protect from forgery -->
      <input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>">

      <!-- Label and input for trainer_id -->
      <div class="form-group">
        <label for="trainer_id" class="control-label">
          Trainer
        </label>

        <%= select_tag(:trainer_id, options_from_collection_for_select(Trainer.all, :id, :name, @lesson.trainer_id), :class => "form-control") %>
      </div>

      <!-- Label and input for lesson_time -->
      <div class="form-group">
        <label for="lesson_time" class="control-label">
          Lesson time
        </label>

        <input type="text" id="lesson_time" name="lesson_time" placeholder="Lesson time" class="form-control" value="<%= @lesson.lesson_time %>">
      </div>

      
      

      <button class="btn btn-warning">
        Update Lesson
      </button>
      or
      <a href="/lessons/<%= @lesson.id %>">Cancel</a>
    </form>
  </div>
</div>

app/views/lessons/index.html.erb
<div class="page-header">
  <h1>
    <a <a href="/lessons">Perfecta Farm Lesson Schedule </a>
    <% if @week == nil %>
    <a href="/lessons/1" class="btn btn-md btn-default">Next week</a>
    <%elsif @week == '1' %>
    <a href="/lessons" class="btn btn-md btn-default">Last week</a>
    <a href="/lessons/<%= @week.to_i + 1 %>" class="btn btn-md btn-default">Next week</a>
    <%else %>
    <a href="/lessons/<%= @week.to_i - 1 %>" class="btn btn-md btn-default">Last week</a>
    <a href="/lessons/<%= @week.to_i + 1 %>" class="btn btn-md btn-default">Next week</a>
  </h1>

  <% end %>
</div>

<div class="row">
  <div class="col-md-12">
    <table class="table table-striped table-hover">
      <% if @week == nil %>
      <tr>
        <th>Time</th>
        <th colspan=2>Tuesday <p><%= Chronic.parse('tuesday of this week').strftime('%m/%e') %></p></th>
        <th colspan=2>Wednesday <p><%= Chronic.parse('wednesday of this week').strftime('%m/%e') %></p></th>
        <th colspan=2>Thursday <p><%= Chronic.parse('thursday of this week').strftime('%m/%e') %></p></th>
        <th colspan=2>Friday <p><%= Chronic.parse('friday of this week').strftime('%m/%e') %></p></th>
        <th colspan=2>Saturday <p><%= Chronic.parse('saturday of this week').strftime('%m/%e') %></p></th>
        <th colspan=2>Sunday <p><%= Chronic.parse('sunday of this week').strftime('%m/%e') %></p></th>
      </tr>

      <% @lesson_options.each do |time| %>
      <tr>
        <td><%= time %></td>
      <% @weekday.each do |day| %>
        <td>
          <% if Chronic.parse("this week #{day} at 12:00 AM") > Time.now %>
          <% if Lesson.where({:student => current_student.id, :lesson_time => Chronic.parse("this week #{day} at #{time}") }).any? == false %>
          <a href="/lessons/new/<%=Chronic.parse("#{day} of this week").strftime('%B_%e')%>_<%=time%>" class="btn btn-xs btn-success">+</a>
          <%else%>
          <a href="/delete_lesson/<%= Lesson.where({:student => current_student.id, :lesson_time => Chronic.parse("this week #{day} at #{time}") }).pluck(:id).to_sentence%>" class="btn btn-xs btn-danger">-</a>
          <%end%>
          <%end%>
        </td>
        <td>
        <% @lessons.each do |lesson| %>
        <% if lesson.lesson_time == Chronic.parse("this week #{day} at #{time}") %>
        <% if current_student.role == 'Trainer' %>
        <p>
        <a href="/lessons/detail/<%= lesson.id %>">
          <%= lesson.trainer.name %>- <%= lesson.student.name %>
          </a>
          <%else%>
          <%= lesson.trainer.name %>- <%= lesson.student.name %>
          <%end%>
        </p>
          <% end %>
          <% end %>
          <% end %>
        </td>
        <% end %>
      </tr>
      <% elsif @week == '1' %>
      <tr>
        <th>Time</th>
        <th colspan=2>Tuesday <p><%= Chronic.parse('tuesday of next week').strftime('%m/%e') %></p></th>
        <th colspan=2>Wednesday <p><%= Chronic.parse('wednesday of next week').strftime('%m/%e') %></p></th>
        <th colspan=2>Thursday <p><%= Chronic.parse('thursday of next week').strftime('%m/%e') %></p></th>
        <th colspan=2>Friday <p><%= Chronic.parse('friday of next week').strftime('%m/%e') %></p></th>
        <th colspan=2>Saturday <p><%= Chronic.parse('saturday of next week').strftime('%m/%e') %></p></th>
        <th colspan=2>Sunday <p><%= Chronic.parse('sunday of next week').strftime('%m/%e') %></p></th>
      </tr>

      <% @lesson_options.each do |time| %>
      <tr>
        <td><%= time %></td>
      <% @weekday.each do |day| %>
        <td>
          <% if Lesson.where({:student => current_student.id, :lesson_time => Chronic.parse("next week #{day} at #{time}") }).any? == false %>
          <a href="/lessons/new/<%=Chronic.parse("#{day} of next week").strftime('%B_%e')%>_<%=time%>" class="btn btn-xs btn-success">+</a>
          <%else%>
          <a href="/delete_lesson/<%= Lesson.where({:student => current_student.id, :lesson_time => Chronic.parse("next week #{day} at #{time}") }).pluck(:id).to_sentence%>" class="btn btn-xs btn-danger">-</a>
          <%end%>
        </td>
        <td>
        <% @lessons.each do |lesson| %>
        <% if lesson.lesson_time == Chronic.parse("next week #{day} at #{time} ") %>
        <% if current_student.role == 'Trainer' %>
        <p>
        <a href="/lessons/detail/<%= lesson.id %>">
          <%= lesson.trainer.name %>- <%= lesson.student.name %>
          </a>
          <%else%>
          <%= lesson.trainer.name %>- <%= lesson.student.name %>
          <%end%>
        </p>
          <% end %>
          <% end %>
          <% end %>
        </td>
        <% end %>
      </tr>
      <% else %>
      <tr>
        <th>Time</th>
        <th colspan=2>Tuesday <p><%= Chronic.parse("#{@week} weeks from now tuesday").strftime('%m/%e') %></p></th>
        <th colspan=2>Wednesday <p><%= Chronic.parse("#{@week} weeks from now wednesday").strftime('%m/%e') %></p></th>
        <th colspan=2>Thursday <p><%= Chronic.parse("#{@week}  weeks from now thursday").strftime('%m/%e') %></p></th>
        <th colspan=2>Friday <p><%= Chronic.parse("#{@week} weeks from now friday").strftime('%m/%e') %></p></th>
        <th colspan=2>Saturday <p><%= Chronic.parse("#{@week} weeks from now saturday").strftime('%m/%e') %></p></th>
        <th colspan=2>Sunday <p><%= Chronic.parse("#{@week} weeks from now sunday").strftime('%m/%e') %></p></th>
      </tr>

      <% @lesson_options.each do |time| %>
      <tr>
        <td><%= time %></td>
      <% @weekday.each do |day| %>
        <td>
          <% if Lesson.where({:student => current_student.id, :lesson_time => Chronic.parse("#{@week} weeks from now #{day} at #{time}") }).any? == false %>
          <a href="/lessons/new/<%=Chronic.parse("#{@week} weeks from now #{day} ").strftime('%B_%e')%>_<%=time%>" class="btn btn-xs btn-success">+</a>
          <%else%>
          <a href="/delete_lesson/<%= Lesson.where({:student => current_student.id, :lesson_time => Chronic.parse("#{@week} weeks from now #{day} at #{time}") }).pluck(:id).to_sentence%>" class="btn btn-xs btn-danger">-</a>
          <%end%>
        </td>
        <td>
        <% @lessons.each do |lesson| %>
        <% if lesson.lesson_time == Chronic.parse("#{@week} weeks from now #{day} at #{time} ") %>
        <% if current_student.role == 'Trainer' %>
        <p>
        <a href="/lessons/detail/<%= lesson.id %>">
          <%= lesson.trainer.name %>- <%= lesson.student.name %>
          </a>
          <%else%>
          <%= lesson.trainer.name %>- <%= lesson.student.name %>
          <%end%>
        </p>
          <% end %>
          <% end %>
          <% end %>
        </td>
        <% end %>
      </tr>
      <% end %>

    </table>

  </div>
</div>

app/views/lessons/new.html.erb
<!-- <br><br><br>
Time: <%= @chronictime %><br>
Day: <%= @chronictime.wday %><br>
Hour: <%= @chronictime.hour %><br>
Min: <%= @chronictime.min %><br> -->

<% trainers_available = [] %>
<% Trainer.all.each do |trainer| %>
<% if Lesson.where({:lesson_time => @chronictime, :trainer_id => trainer.id }).any? == false && %>
<% trainer.name%>
<% if @chronictime.wday == 2 %>
  <% if Chronic.parse("today at #{trainer.tues_start_hour}:#{trainer.tues_start_min} #{trainer.tues_start_am_pm}") <= Chronic.parse("today at #{@chronictime.hour}:#{@chronictime.min}") %>
  <% if Chronic.parse("today at #{trainer.tues_end_hour}:#{trainer.tues_end_min} #{trainer.tues_end_am_pm}") > Chronic.parse("today at #{@chronictime.hour}:#{@chronictime.min}") %>
  <%trainer.name %>
<% trainers_available.push trainer.id %>
<% end %>
<% end %>
<% end %>
<% if @chronictime.wday == 3 %>
  <% if Chronic.parse("today at #{trainer.wed_start_hour}:#{trainer.wed_start_min} #{trainer.wed_start_am_pm}") <= Chronic.parse("today at #{@chronictime.hour}:#{@chronictime.min}") %>
  <% if Chronic.parse("today at #{trainer.wed_end_hour}:#{trainer.wed_end_min} #{trainer.wed_end_am_pm}") > Chronic.parse("today at #{@chronictime.hour}:#{@chronictime.min}") %>
  <%trainer.name %>
<% trainers_available.push trainer.id %>
<% end %>
<% end %>
<% end %>
<% if @chronictime.wday == 4 %>
  <% if Chronic.parse("today at #{trainer.thur_start_hour}:#{trainer.thur_start_min} #{trainer.thur_start_am_pm}") <= Chronic.parse("today at #{@chronictime.hour}:#{@chronictime.min}") %>
  <% if Chronic.parse("today at #{trainer.thur_end_hour}:#{trainer.thur_end_min} #{trainer.thur_end_am_pm}") > Chronic.parse("today at #{@chronictime.hour}:#{@chronictime.min}") %>
  <% trainer.name %>
<% trainers_available.push trainer.id %>
<% end %>
<% end %>
<% end %>
<% if @chronictime.wday == 5 %>
  <% if Chronic.parse("today at #{trainer.fri_start_hour}:#{trainer.fri_start_min} #{trainer.fri_start_am_pm}") <= Chronic.parse("today at #{@chronictime.hour}:#{@chronictime.min}") %>
  <% if Chronic.parse("today at #{trainer.fri_end_hour}:#{trainer.fri_end_min} #{trainer.fri_end_am_pm}") > Chronic.parse("today at #{@chronictime.hour}:#{@chronictime.min}") %>
  <% trainer.name %>
<% trainers_available.push trainer.id %>
<% end %>
<% end %>
<% end %>
<% if @chronictime.wday == 6 %>
  <% if Chronic.parse("today at #{trainer.sat_start_hour}:#{trainer.sat_start_min} #{trainer.sat_start_am_pm}") <= Chronic.parse("today at #{@chronictime.hour}:#{@chronictime.min}") %>
  <% if Chronic.parse("today at #{trainer.sat_end_hour}:#{trainer.sat_end_min} #{trainer.sat_end_am_pm}") > Chronic.parse("today at #{@chronictime.hour}:#{@chronictime.min}") %>
  <% trainer.name %><br>
<% trainers_available.push trainer.id %>
<% end %>
<% end %>
<% end %>
<% if @chronictime.wday == 0 %>
  <% if Chronic.parse("today at #{trainer.sun_start_hour}:#{trainer.sun_start_min} #{trainer.sun_start_am_pm}") <= Chronic.parse("today at #{@chronictime.hour}:#{@chronictime.min}") %>
  <% if Chronic.parse("today at #{trainer.sun_end_hour}:#{trainer.sun_end_min} #{trainer.sun_end_am_pm}") > Chronic.parse("today at #{@chronictime.hour}:#{@chronictime.min}") %>
  <% trainer.name %>
<% trainers_available.push trainer.id %>
<% end %>
<% end %>
<% end %>
<% end %>
<% end %>
<!-- Trainers available: <%= trainers_available %> -->

<% if trainers_available.length == 0 %>
<h3>Sorry no lessons available</h3>

<a href="<%=@referer%>">Cancel</a>

<% else %>
<!-- Validation failure messages -->
<% if @lesson.errors.any? %>
  <% @lesson.errors.full_messages.each do |message| %>
    <div class="alert alert-dismissable alert-danger">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= message %>
    </div>
  <% end %>
<% end %>

<div class="page-header">
  <h3>Add Lesson at <%= @chronictime.strftime('%l:%M %p') %></h3>
</div>


<% if current_student.role == 'Trainer' %>
<div class="row">
  <div class="col-md-12">
    <form action="/create_lesson" method="post">
      <!-- Hidden input for authenticity token to protect from forgery -->
      <input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>">

      <!-- Label and input for trainer_id -->
      <div class="form-group">
        <label for="trainer_id" class="control-label">
          Trainer
        </label>

        <%= select_tag(:trainer_id, options_from_collection_for_select(Trainer.where(:id => trainers_available), :id, :name, @lesson.trainer_id), :class => "form-control") %>
      </div>

      <!-- Label and input for student_id -->
      <div class="form-group">
        <label for="student_id" class="control-label">
          Student
        </label>

        <%= select_tag(:student_id, options_from_collection_for_select(Student.all, :id, :name, @lesson.student_id), :class => "form-control") %>
      </div>

      <!-- Label and input for lesson_time -->
      <input type="hidden" id="lesson_time" name="lesson_time" placeholder="Lesson time" class="form-control" value="<%= @chronictime %>">
      <input type="hidden" id="lesson_time" name="lesson_page"  class="form-control" value="<%= @referer %>">
      </div>
      <%else%>
<div class="row">
  <div class="col-md-12">
    <form action="/create_lesson" method="post">
      <!-- Hidden input for authenticity token to protect from forgery -->
      <input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>">

      <!-- Label and input for trainer_id -->
      <div class="form-group">
        <label for="trainer_id" class="control-label">
          Trainer
        </label>

        <%= select_tag(:trainer_id, options_from_collection_for_select(Trainer.where(:id => trainers_available), :id, :name, @lesson.trainer_id), :class => "form-control") %>
      </div>

      <!-- Label and input for student_id -->
      <input type="hidden" id="student_id" name="student_id" placeholder="Student" class="form-control" value="<%= current_student.id %>">



      <!-- Label and input for lesson_time -->

        <input type="hidden" id="lesson_time" name="lesson_time" placeholder="Lesson time" class="form-control" value="<%= @chronictime %>">

        <input type="hidden" id="lesson_time" name="lesson_page"  class="form-control" value="<%= @referer %>">

<%end%>
      <button class="btn btn-success">
        Create Lesson
      </button>
      or
      <a href="<%=@referer%>">Cancel</a>
    </form>
  </div>
</div>
<%end%>

app/views/lessons/show.html.erb
<div class="page-header">
  <h3>Lesson #<%= @lesson.id %></h3>
</div>

<div class="row">
  <div class="col-md-12 mb-2">
    <dl class="dl-horizontal">
      <dt>Trainer</dt>
      <dd>
        <%= @lesson.trainer.name %>
      </dd>

      <dt>Lesson time</dt>
      <dd><%= @lesson.lesson_time.strftime('%b %e, %l:%M %p') %></dd>

      <dt>Student</dt>
      <dd>
          <%= @lesson.student.name %>
      </dd>

    </dl>

    <div class="btn-group btn-group-justified">
      <a href="/lessons" class="btn btn-primary">
        Back
      </a>
        <a href="/delete_lesson/<%= @lesson.id %>" class="btn btn-danger" rel="nofollow">
          Delete
        </a>
    </div>
  </div>
</div>